### ISSUE TITLE
Broken with last build of ng2-idle

### ISSUE THREAD

**Issue by patrickracicot** [HackedByChinese/ng2-idle-keepalive#10]
In the last build of ng2-idle, their has been a modification of the Module.
Basicly when importing ng2-idle in our app we now point directly on ng2-idle instead of ng2-idle/core.
The bug is that in ng2-idle-keepalive, the import statements have not been updated and they still point to ng2-idle/core.

**core.ts**
`import {KeepaliveSvc} from 'ng2-idle/core'; `
should be 
`import {KeepaliveSvc} from 'ng2-idle;`

**keepalive.ts**
`import {KeepaliveSvc} from 'ng2-idle/core';`
should be
`import {KeepaliveSvc} from 'ng2-idle';`

**Comment by cmdickson** [comment]
The dependency on ng2-idle is also locked at 1.0.0-alpha.17 in package.json

**Comment by HackedByChinese** [comment]
Yeah, I updated keepalive but I am having trouble figuring out the commonjs bundling i've been doing. Might switch both to UMD like Angular did.

**Comment by HackedByChinese** [comment]
Please note that this module has been moved to the ng2-idle repository.
