### ISSUE TITLE
Relaxing Angular Dependencies Even More

### ISSUE THREAD

**Issue by AHelper** [HackedByChinese/ng2-idle-keepalive#11]
Following Angular 2's observance of semantic versioning, it would be nice to target major versions (same for ng2-idle) rather than minor as breaking API changes in Angular should be deferred now until a major version release.  Running `gulp test` when targeting angular ^2.0.0 passes.

**Comment by HackedByChinese** [comment]
Please note that this module has been moved to the ng2-idle repository.
