### ISSUE TITLE
Keep getting: Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by webtrix** [HackedByChinese/ng2-idle-keepalive#3]
Wanted to try out this script idle & keepalive on my NG2 project (beta9) but I keep getting this error, don't really know what's the problem to be honest.

**Comment by HackedByChinese** [comment]
Not sure if it's related to this module being built against beta.3 or not. I will be refreshing these modules to latest anyways. Do you have an example or anything somewhere I can examine it?

**Comment by webtrix** [comment]
I think it has something to do with my systemjs code in my index.html and maybe my tsconfig.json .. I use the one supplied by angular.io in their quickstart.

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "gulpfile.js",
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}
```

```javascript
<script>
      System.config({
        map: {
          rxjs: 'node_modules/rxjs'
        },
        packages: {
          app: {
            format: 'register',
            defaultExtension: 'js'
          },
          rxjs: {
            defaultExtension: 'js'
          }
        }
      });
      System.import('app/boot').then(null, console.error.bind(console));
</script>
```

**Comment by HackedByChinese** [comment]
Please note this module has been moved to the ng2-idle repository.
