### ISSUE TITLE
 Unexpected token <

### ISSUE THREAD

**Issue by noagr1** [HackedByChinese/ng2-idle-keepalive#5]
Hi, 
I really want to use this package but with no luck - I am new to angular2 and web programming but I do have a working app and really want to use your module top handle the idle instead of writing it by myself...

Error: SyntaxError: Unexpected token <
	    at Object.eval (http://127.0.0.1:8080/node_modules/ng2-idle/core.js:12:14)
	    at eval (http://127.0.0.1:8080/node_modules/ng2-idle/core.js:33:4)
	Evaluating http://127.0.0.1:8080/src/@angular/core
	Evaluating http://127.0.0.1:8080/node_modules/ng2-idle/core.js
	Error loading http://127.0.0.1:8080/src/app/main.js

The @angular/core is of version  core@2.0.0-rc.1

Thanks

**Comment by patrickracicot** [comment]
+1 the bug if indeed here.

The ng2-idle library recently had an update to support RC.1.
We basically need the same fix here.

**Comment by noagr1** [comment]
Thanks @patrickracicot 
I have tried the suggested solution here:
[](http://stackoverflow.com/questions/37568779/angular2-user-active-and-idle/37568959#37568959)
and it worked.
Thanks a lot
