### ISSUE TITLE
Alpha.6 not available via npm

### ISSUE THREAD

**Issue by cmdickson** [HackedByChinese/ng2-idle-keepalive#6]
npm is reporting alpha.5 as the latest version available, so unable to use with Angular 2 RC.3

The corresponding ng2-idle (alpha.12) for use with Angular 2 RC.3 is available

> npm show ng2-idle-keepalive version
> 1.0.0-alpha.5

> npm show ng2-idle version
> 1.0.0-alpha.12

> npm install
> ...
> npm ERR! No compatible version found: ng2-idle-keepalive@^1.0.0-alpha.6
> npm ERR! Valid install targets:
> npm ERR! 1.0.0-alpha.5, 1.0.0-alpha.4, 1.0.0-alpha.3, 1.0.0-alpha.2, 1.0.0-alpha.1

**Comment by HackedByChinese** [comment]
Sorry, forgot to publish it.
