### ISSUE TITLE
keepalive with full Request fails

### ISSUE THREAD

**Issue by DavidRSchaller** [HackedByChinese/ng2-idle-keepalive#8]
Regarding this following:
`// will assume a GET request; you can specify a full Request object if you need something else, want to include headers, etc.
keepalive.request('/path/to/endpoint');`

My code:

`import {Request, Headers, RequestMethod} from '@angular/http';`

`let headers = new Headers({ 'Authorization': 'Bearer ' + sessionStorage.getItem( 'Token' ) });`
`let pingReq: Request = new Request({method: RequestMethod.Get, url: appSettings.get().apiuri + '/authorization/refreshtoken', headers: headers });`
`keepalive.request( pingReq  );
`

Error:

`Argument of type 'Request' is not assignable to parameter of type 'string | Request'.
  Type 'Request' is not assignable to type 'Request'.`

**Comment by smorks** [comment]
i believe this is an issue due to Angular slightly changing their Request object between RC4 & RC5. @DavidRSchaller, can you confirm you are using Angular RC5?

**Comment by DavidRSchaller** [comment]
Yes, I am on RC5, so the request object difference sounds like the culprit. I do not recall whether I had the package in place while utilizing RC4 for comparison.

**Comment by HackedByChinese** [comment]
ng2-idle@1.0.0-alpha.15 and ng2-idle-keepalive@1.0.0-alpha.8 are updated for RC.5
